### ISSUE TITLE
arale 4月份工作重点

### ISSUE THREAD

**Issue by popomore** [aralejs/aralejs.org#249]
- [x] #246 配合 spm2 发布，arale gallery 重新 build
- [x] alice 重新 build
- [ ] aralejs/widget#37 widget 1.1.0
- [x] spmjs/spm-alipay-suite#1 一体化工具基本可用
- gallery 和 arale 的管理方案
